Add driver collector
lab259/go-rscsrv-prometheus pull request #3
Opened 2020-01-03 12:15 UTC by chicobentojr

### :sparkles: Enhancements

* Add collector to capture sql client metrics to publish using prometheus

2020-01-03 20:24 UTC, jamillosantos requested changes
Please, consider adding a full example (:star2: with docker-compose) to show how to use it.

Also, would be nice to write some documentation.

2020-01-03 20:24 UTC, jamillosantos commented on promsql/driver_collector.go
> +		ExecutionErroneousAmountCounter:    prometheus.NewCounter(prometheus.CounterOpts{}),
I think you should be adding names and descriptions for those metrics.

Remember adding the prefix.

2020-01-15 11:28 UTC, jamillosantos requested changes
After creating this extension, I think now you are able to better understand (and I too) where we want to go with these metrics. That said...

What are we measuring with `TransactionFailedCounter`? And what do we want/need to measure while dealing with transactions?

2020-01-15 11:28 UTC, jamillosantos commented on promsql/driver_collector.go
> +		descQueryTotalCounter:            prometheus.NewDesc(fmt.Sprintf("db_%squery_total", prefix), "The total number of queries processed.", nil, nil),
The `prometheus.CounterOpts` has this information about the name and "help" text. Use them instead of creating a `NewDesc`.

2020-01-20 18:46 UTC, felipemfp approved these changes
LGTM :tada::+1:

2020-01-21 20:09 UTC, jamillosantos approved these changes

2020-01-21 20:14 UTC, merged