Add query collector
lab259/go-rscsrv-prometheus pull request #4
Opened 2020-01-22 13:06 UTC by chicobentojr

### :sparkles: Enhancements

* Add QueryCollector to capture metrics from a specific query (i.e. `NamedQuery`)

### :pencil: Documentation

* Add a QueryCollector usage example with hermes

2020-01-22 19:02 UTC, jamillosantos requested changes

2020-01-22 19:02 UTC, jamillosantos commented on promquery/query_collector.go
> +var queryCollectorLabels = []string{"queryName"}
```suggestion
var queryCollectorLabels = []string{"name"}
```

2020-01-22 19:02 UTC, jamillosantos commented on promquery/query_collector.go
> +				Name: fmt.Sprintf("db_%stotal_calls", prefix),
```suggestion
				Name: fmt.Sprintf("namedqry_%stotal_calls", prefix),
```

Also, apply it to the other metrics.

2020-01-23 19:28 UTC, felipemfp approved these changes
LGTM :tada::+1:

2020-01-24 00:05 UTC, jamillosantos approved these changes

2020-01-24 00:05 UTC, merged