Add exec collector
lab259/go-rscsrv-prometheus pull request #5
Opened 2020-01-22 15:19 UTC by chicobentojr

### :sparkles: Enhancements

* Add `TotalRowsAffected` metric to `QueryCollector`
* Add `Exec` and `ExecContext` methods to `QueryCollector` (this will enable SQL commands as INSERT, UPDATE and DELETE)

2020-01-22 19:07 UTC, jamillosantos requested changes
This problem is the reflection of the review on the previous PR (that this one is based on) #4.

2020-01-22 19:07 UTC, jamillosantos commented on promquery/query_collector.go
> +				Name: fmt.Sprintf("db_%stotal_rows_affected", prefix),
```suggestion
				Name: fmt.Sprintf("namedqry_%stotal_rows_affected", prefix),
```

2020-01-23 18:44 UTC, felipemfp approved these changes
LGTM :tada::+1:

2020-01-24 00:06 UTC, jamillosantos approved these changes

2020-01-24 00:10 UTC, merged